[package]
name = "coredump_bot"
version = "0.2.5"
authors = [
  "Stefan Schindler <stefan@estada.ch>"
]

[dependencies]
telegram-bot = { git = "https://github.com/dns2utf8/telegram-bot.git", branch = "fix_types" }
hyper = "0.6"
rustc-serialize = "0.3"
spaceapi = { git = "https://github.com/coredump-ch/spaceapi-rs.git", branch = "master" }
